/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marioinga' at '10/13/16 6:32 PM' with Gradle 3.1
 *
 * @author marioinga, @date 10/13/16 6:32 PM
 */
package hello;

import static spark.Spark.*;


public class App {
  public static void main(String[] args) {
    get("/hello", (req, res) -> "Hello World");
  }

  /*
  public static void main(String[] args) {
    System.out.println("Hello world");
  }
  */

  /*
    public boolean someLibraryMethod() {
        return true;
    }
  */
}
